### ISSUE TITLE
错别字捉虫

### ISSUE THREAD

**Issue by hrQAQ** [Super-BUAA-2021/GinBook#2]
https://super-buaa-2021.github.io/GinBook/post/preparation/3.html#configinitviper
捉个虫，jwt配置第一行有错别字，生产环境时**记得**修改
```
database:
  ip: '127.0.0.1' # MySQL的IP地址
  port: '3306' # MySQL的端口
  user: 'username' # MySQL的用户名
  password: 'password' # MySQL对应用户的密码
  database: 'dbname' # 使用的MySQL数据库名称

jwt:
  # token 密钥，生产环境时及的修改
  secret: 'demo@'
  # token 过期时间 单位：秒
  timeout: 3600

server:
  backend_url: 'http://127.0.0.1:8081/api/v1'
```

https://super-buaa-2021.github.io/GinBook/post-basis/p7-gorm-basic-and-service.html#%E7%AC%AC%E4%B8%83%E7%AB%A0%EF%BC%9A%E5%88%9D%E8%AF%86grom%E4%BD%BF%E7%94%A8gorm%E8%BF%9B%E8%A1%8C%E6%95%B0%E6%8D%AE%E5%BA%93%E6%93%8D%E4%BD%9C

捉虫处加粗了

ORM（对象关系**映射**）可以在关系型数据库与对象之间建立映射，可以想操纵对象一样操作数据库。而在Go中，我所指的有Gorm与Beego ORM两种ORM库用一操作数据库。而本Book中选择Gorm。
